"""
LendingLoopAaveWBTCUSDC Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LendingLoopAaveWBTCUSDCStrategy
except ImportError:
    from strategy import LendingLoopAaveWBTCUSDCStrategy

__all__ = [
    "LendingLoopAaveWBTCUSDCStrategy",
]
